---
driver:
  name: docker
  hostname: aodh.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: aodh
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
    - name: apache
      repo: git
      source: https://github.com/salt-formulas/salt-formula-apache
  state_top:
    base:
      "*":
        - linux.system
        - aodh
  pillars:
    release.sls:
      aodh:
        server:
          version: <%= ENV['OS_VERSION'] || 'pike' %>
    ssl.sls:
      aodh:
        server:
          identity:
            protocol: https
          database:
            x509:
              enabled: True
              ca_file: /etc/aodh/ssl/mysql/ca-cert.pem
              key_file: /etc/aodh/ssl/mysql/client-key.pem
              cert_file: /etc/aodh/ssl/mysql/client-cert.pem
              cacert: |
                -----BEGIN CERTIFICATE-----
                MIIFzzCCA7egAwIBAgIIe7zZ8hCvkgowDQYJKoZIhvcNAQELBQAwSjELMAkGA1UE
                -----END CERTIFICATE-----
              cert: |
                -----BEGIN CERTIFICATE-----
                MIIGSjCCBDKgAwIBAgIJAIHRPs2rZbLvMA0GCSqGSIb3DQEBCwUAMEoxCzAJBgNV
                -----END CERTIFICATE-----
              key: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIJKQIBAAKCAgEAq0m4kOIITliYea07yJnlSRNY0o6NaykiteSfHGauiub4lNQJ
                -----END RSA PRIVATE KEY-----
            ssl:
              enabled: True
              cacert_file: /etc/aodh/ssl/mysql/ca-cert.pem
              cacert: |
                -----BEGIN CERTIFICATE-----
                MIIFzzCCA7egAwIBAgIIe7zZ8hCvkgowDQYJKoZIhvcNAQELBQAwSjELMAkGA1UE
                -----END CERTIFICATE-----
          message_queue:
            port: 5671
            ssl:
              enabled: True
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - aodh
          - release
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_mcp_openstack_<%= ENV['OS_VERSION'] || 'pike' %>.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: server_cluster
    provisioner:
      pillars-from-files:
        aodh.sls: tests/pillar/server_cluster.sls

  - name: server_single
    provisioner:
      pillars-from-files:
        aodh.sls: tests/pillar/server_single.sls

  - name: server_cluster_ssl
    provisioner:
      pillars-from-files:
        aodh.sls: tests/pillar/server_cluster.sls
      pillars:
        top.sls:
          base:
            "*":
              - linux_repo_openstack
              - aodh
              - release
              - ssl

  - name: server_single_ssl
    provisioner:
      pillars-from-files:
        aodh.sls: tests/pillar/server_single.sls
      pillars:
        top.sls:
          base:
            "*":
              - linux_repo_openstack
              - aodh
              - release
              - ssl

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
